# Generated by Django 6.0.2 on 2026-02-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='is_active',
        ),
        migrations.AddField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
