# Generated by Django 6.0.2 on 2026-02-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_verification_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='purpose',
            field=models.CharField(choices=[('account_verification', 'Acount verification'), ('password_reset', 'Password reset'), ('account_deactivation', 'Account deactivation')], default='abc', max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['user', 'purpose'], name='accounts_ve_user_id_247e74_idx'),
        ),
    ]
