# Generated by Django 6.0.2 on 2026-02-21 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verification_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='purpose',
            field=models.CharField(choices=[('account_verification', 'Account verification'), ('password_reset', 'Password reset'), ('account_deactivation', 'Account deactivation')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
