# Generated by Django 6.0.5 on 2026-09-04 04:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_description_brand_image_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
