# Generated by Django 6.0.5 on 2026-09-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
    ]
