# Generated by Django 6.0.5 on 2026-05-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='HeroSection',
        ),
    ]
