# Generated by Django 6.0.5 on 2026-05-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_faqquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='faq_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='page.faqsection'),
        ),
    ]
