# Generated by Django 6.0.5 on 2026-09-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_otherpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
