# Generated by Django 6.0.5 on 2026-09-04 04:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_contactsection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
