# Generated by Django 6.0.5 on 2026-05-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='fav_icon',
            field=models.ImageField(blank=True, null=True, upload_to='identity/'),
        ),
    ]
