# Generated by Django 6.0.5 on 2026-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0002_identity_fav_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_media/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
