# Generated by Django 6.0.5 on 2026-09-04 04:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0003_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
